export const REAL_WEBTOONS = [
    {
        id: "nano-singularity",
        title: "나노 싱귤래리티",
        author: "AI 오토마톤",
        genre: "SF",
        rating: 4.9,
        thumbnail: "https://image.pollinations.ai/prompt/cyberpunk_seoul_webtoon_cover_nano_singularity?width=400&height=600&nologo=true",
        banner: "https://image.pollinations.ai/prompt/cyberpunk_seoul_webtoon_banner_nano_singularity?width=1920&height=1080&nologo=true",
        description: "2077년 네오 서울, 특이점을 넘어선 나노 머신들의 반란과 이를 막으려는 마지막 해커의 사투.",
        status: "approved",
        isNew: true,
        episodes: [
            { vol: 1, title: "나노 싱귤래리티 1화", cuts: Array.from({ length: 70 }).map((_, i) => `https://image.pollinations.ai/prompt/webtoon_panel_nano_singularity_episode_1_scene_${i}?width=800&height=1200&nologo=true&seed=${i}`) },
            { vol: 2, title: "나노 싱귤래리티 2화", cuts: Array.from({ length: 70 }).map((_, i) => `https://image.pollinations.ai/prompt/webtoon_panel_nano_singularity_episode_2_scene_${i}?width=800&height=1200&nologo=true&seed=${100 + i}`) }
        ],
        createdAt: new Date().toISOString()
    },
    {
        id: "joseon-future-2099",
        title: "조선 퓨처 2099",
        author: "타임 패러독스",
        genre: "판타지",
        rating: 4.8,
        thumbnail: "https://image.pollinations.ai/prompt/korean_traditional_hanbok_neon_cyberpunk_cover?width=400&height=600&nologo=true",
        banner: "https://image.pollinations.ai/prompt/korean_traditional_hanbok_neon_cyberpunk_banner?width=1920&height=1080&nologo=true",
        description: "과거와 미래가 융합된 2099년의 신 조선. 왕실 비밀 호위무사의 시간을 넘나드는 액션 활극.",
        status: "approved",
        isHot: true,
        episodes: [
            { vol: 1, title: "조선 퓨처 2099 1화", cuts: Array.from({ length: 70 }).map((_, i) => `https://image.pollinations.ai/prompt/korean_hanbok_action_webtoon_episode_1_scene_${i}?width=800&height=1200&nologo=true&seed=${200 + i}`) },
            { vol: 2, title: "조선 퓨처 2099 2화", cuts: Array.from({ length: 70 }).map((_, i) => `https://image.pollinations.ai/prompt/korean_hanbok_action_webtoon_episode_2_scene_${i}?width=800&height=1200&nologo=true&seed=${300 + i}`) }
        ],
        createdAt: new Date().toISOString()
    },
    {
        id: "copycat",
        title: "카피 캣",
        author: "도플갱어",
        genre: "미스터리",
        rating: 4.7,
        thumbnail: "https://image.pollinations.ai/prompt/thriller_webtoon_cover_copycat_mirror?width=400&height=600&nologo=true",
        banner: "https://image.pollinations.ai/prompt/thriller_webtoon_banner_copycat_shadow?width=1920&height=1080&nologo=true",
        description: "어느 날 나타난 완벽한 나의 복제인간. 그가 내 자리를 차지하기 시작했다.",
        status: "approved",
        episodes: [
            { vol: 1, title: "카피 캣 1화", cuts: Array.from({ length: 70 }).map((_, i) => `https://image.pollinations.ai/prompt/thriller_webtoon_copycat_episode_1_scene_${i}?width=800&height=1200&nologo=true&seed=${400 + i}`) },
            { vol: 2, title: "카피 캣 2화", cuts: Array.from({ length: 70 }).map((_, i) => `https://image.pollinations.ai/prompt/thriller_webtoon_copycat_episode_2_scene_${i}?width=800&height=1200&nologo=true&seed=${500 + i}`) }
        ],
        createdAt: new Date().toISOString()
    }
];

export const PREMIUM_CITIZEN_NEWS = [
  // 1. 사회/정치
  {
    id: "soc_pol1",
    title: "고령화 시대, 마을 공동체가 답이다: 도심 속 상호 돌봄 네트워크 모델 구축",
    author: "이정훈 기자",
    reporterId: "admin",
    content: "온기가 사그라드는 매서운 겨울철, 늘 홀로 외롭게 도시 골목을 내려다보던 여든의 퇴직 목공 장인 김태석 할아버지의 낡은 대문 앞에는 매주 일요일 아침마다 작은 꽃 한 송이와 편지가 배달됩니다. 이는 이솔나라가 주도하는 '도심 골목 상호 돌봄 네트워크'의 일환으로 매칭된 스물다섯의 프리랜서 디자이너 민우 청년이 건네는 진솔한 안부의 손길입니다. 홀로 남은 노년과 사회적 단절에 허덕이던 청년이 만나 밥상을 함께하고, 나이와 시대를 뛰어넘는 우정을 속삭이며 고독이라는 현대 사회의 깊은 병령을 어루만져 줍니다. 주민들이 직접 조직하고 마음을 모은 상호 순환 식구 네트워크는 행정 사각지대를 가장 인간적이고 따스하게 보완하는 진정한 공동체 복지 모델의 시발점이 되고 있으며, 차갑게 물들어가는 회색빛 도시에 깊은 울림과 연대의 싹을 틔워내고 있습니다.",
    thumbnail: "https://images.unsplash.com/photo-1516594798947-e65505dbb29d?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-12",
    likes: 125,
    category: "사회/정치",
    isApproved: true,
    isFeatured: true,
  },
  {
    id: "soc_pol2",
    title: "풀뿌리 주민 참여 예산 정책의 투명성 강화 및 디지털 민주주의 정착 방안",
    author: "박우정 기자",
    reporterId: "admin",
    content: "발달 장애를 가진 어린 딸을 키우며 세상과의 소통이 막막했던 30대 어머니 은희 씨는 주민참여 예산 전용 앱에 간절한 기사형 글을 남겼습니다. '피부색도, 몸의 기동력도 관계없이 우리 아이들이 넘어지지 않고 한데 뒹굴 수 있는 촉각 배리어프리 무장애 놀이터가 동네 공터에 필요합니다'라는 눈물의 청원이었습니다. 복잡한 정치적 이데올로기 장벽을 넘어, 디지털 영토에서 수천 명의 보이지 않는 주민들은 은희 씨의 글귀에 뜨겁게 공감하며 마음으로 동의 버튼을 눌렀고, 마침내 지자체 예산 집행 1위 과제로 안착되었습니다. 이것은 단순한 풀뿌리 주민 참여 예산제 결과를 뛰어넘어, 첨단 기술이 따뜻한 가슴을 가진 평범한 이웃들과 결합했을 때 어떻게 소외된 자들을 지탱하는 '디지털 휴머니즘'으로 진화할 수 있는지 보여주는 위대한 풀뿌리 실천이자, 사회적 정의와 아름다운 연대의 참모습입니다.",
    thumbnail: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-11",
    likes: 84,
    category: "사회/정치",
    isApproved: true,
  },

  // 2. 경제/문화
  {
    id: "eco_cul1",
    title: "지역 순환 통화의 디지털화: 소상공인 매출 증대와 수수료 상생 비즈니스",
    author: "최경제 연구원",
    reporterId: "admin",
    content: "쇠락해가는 전통 골목시장 귀퉁이에서 30년간 묵묵히 붕어빵과 어묵을 구워오던 정수 할아버지는 높은 대기업 수수료와 물가 상승의 압박으로 폐업을 진지하게 고려하고 있었습니다. 그러나 지역 밀착 자치 독립 통화인 '이솔코인'이 보급되면서 시장 전체가 상생과 나눔의 보금자리로 개벽했습니다. 거래 수수료가 전무한 이솔코인은 지역 내에서 순환하며 소상공인들의 부담을 숨 막히던 터널 밖으로 구출해 냈습니다. 혜택을 받은 정수 할아버지는 아낀 유통 불입 마진으로 근방에서 땀 흘려 가며 밤새 배달 일에 전념하는 청년 기사들에게 매일 뜨거운 어묵국과 호빵을 무상 나눔으로 선사하기 시작했습니다. 돈이 숫자의 단절된 힘을 넘어 생명과 마음의 혈관을 위로하는 신뢰 교환의 매개체로 작용함으로써, 자본주의의 소외된 사막 위에 찬란하고 선한 꽃을 피워냈습니다.",
    thumbnail: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-12",
    likes: 92,
    category: "경제/문화",
    isApproved: true,
  },
  {
    id: "eco_cul2",
    title: "글로벌 K-컬처 열풍 아래 기초 예술 연대 및 순수 창작자 생태계 보호 대책",
    author: "김문화 평론가",
    reporterId: "admin",
    content: "화려한 스포트라이트가 비치는 글로벌 대작 콘서트의 이면에는, 보이지 않는 지하실에서 땀방울을 한 방울씩 흘리며 연극 무대를 채우는 청년 극단 단원들과 기초 문학 창작자들이 숨어 있습니다. '우리가 무대를 가꾸는 것은 돈이 목적이 아닙니다. 오직 단 한 사람의 영혼이라도 우리 연극을 보고 삶의 희망과 화해를 찾을 수 있다면, 그것으로 굶주림마저 영광으로 채웁니다'라고 고백하는 고달픈 청년 창작자들. 이솔뉴스는 이들의 영혼어린 독백을 가벼운 엔터테인먼트 가십거리가 아니라, 현대 인간성 보전을 위한 지고의 가치로 세상에 타전하기 시작했습니다. 기초 소양 예술 창작자들을 위한 공적 지원과 그들의 자존을 세워주는 사회적 무대는, 한 나라의 문화적 기초 체력을 넘어 인간 실존을 성찰하고 다듬는 든든한 방패 역할을 하고 있으며 대중들에게 깊은 성찰의 물결을 퍼트리고 있습니다.",
    thumbnail: "https://images.unsplash.com/photo-1514466750727-39f3f2959c7e?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-12",
    likes: 110,
    category: "경제/문화",
    isApproved: true,
  },

  // 3. 복지/미래비전
  {
    id: "wel_fut1",
    title: "비건 라이프와 첨단 인공지능이 만나는 '이솔나라 스마트 시티' 스마트 돌봄",
    author: "희망브리지",
    reporterId: "admin",
    content: "고도로 발달한 스마트 시티의 첨단 알고리즘은 거리를 지나는 차의 번호판을 식별하는 데에만 쓰이지 않습니다. 이솔나라 복지부의 원격 보살핌 AI '수케어'는, 주말 동안 보일러 전기 전력량이 급감하거나 조도가 변화하지 않는 은둔 고독 가구의 작은 신호를 민감하게 포착합니다. 기계가 보내온 섬세한 위기 노드를 탐색한 주민 봉사단원들은 즉시 문을 두드려 차가운 손을 감싸고, 함께 유기농 비건 채식 화분을 분양하며 세상 밖으로 걸어 나오도록 미소를 건냅니다. 첨단 기술의 완성이 인간을 기계의 종속물로 만드는 것이 아니라, 단 한 명의 생명도 벼랑 끝으로 추락하지 않도록 보호하는 '스마트 소셜 안식처'의 완성에 있음을, 전 지구가직시하고 깊은 안도를 속삭이고 있습니다.",
    thumbnail: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-12",
    likes: 232,
    category: "복지/미래비전",
    isApproved: true,
  },
  {
    id: "wel_fut2",
    title: "기술 윤리와 인간 존엄의 정점: AI가 대체하는 노동과 미래 기본소득 제도",
    author: "이솔 AI 연구원",
    reporterId: "admin",
    content: "인간이 지녀온 지식 노동과 창작 영역마저 기계 지능에 양도되어 가는 신해상도의 특이점 시대, 우리는 질문해야 합니다. '인간의 가치는 오직 일터에서의 가동 효율성과 생산성에 의해서만 매겨지는가?' 이솔 AI 발전소의 심포지엄은, 일자리를 기계에 일임한 대가로 생성된 막대한 테크 이익을 모든 생명체들의 기본권 유지를 위한 '지구 배당형 기본소득' 제도로 전환해야 한다고 역설했습니다. 노동의 고달픈 멍에에서 해방된 인류가 비로소 시를 읊조리고, 들꽃의 존재에 감탄하며, 이웃과의 따뜻한 담소에 몰두하는 세상을 꿈꿉니다. 인공지능과의 상생은 인간 존재의 종말이 아닌, 비로소 인간이 인간 본연의 존엄성과 우주적 존재 의의를 자각하는 새로운 르네상스의 여명입니다.",
    thumbnail: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-12",
    likes: 310,
    category: "복지/미래비전",
    isApproved: true,
    isFeatured: true,
  },

  // 4. 만평
  {
    id: "cart1",
    title: "[이솔만평] 고물가 시대의 이면, 무거운 가방을 멘 우리들의 가장",
    author: "현원감독",
    reporterId: "admin",
    content: "치솟는 물가와 불안정한 생활 경비 속에서, 매일 새벽 차가운 겨울 안개를 헤치며 인력 시장으로, 배달 길로 나서는 우리의 부모님들. 현원감독은 그들의 어깨 위 무거운 짐을 풍자와 연민이 교차하는 아름다운 먹선과 우아한 수채물감 색채로 담아냈습니다. 단순한 물가 폭등 고발을 넘어, 보이지 않는 곳에서 가족이라는 소우주를 지탱하기 위해 흔들림 없이 한 걸음을 내딛는 우리 주위 모든 평범한 영웅들의 헌신을 기록하며 영혼을 관통하는 위로를 전합니다.",
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-12",
    likes: 456,
    category: "만평",
    isApproved: true,
  },
  {
    id: "cart2",
    title: "[이솔만평] 초연결 인공지능 탐식, 창작자의 권익은 영광의 그늘 아래에",
    author: "현원감독",
    reporterId: "admin",
    content: "인터넷 바다에 존재하는 수천만 명의 소규모 화백들의 거친 스케치와 혼이 깃든 채색 원화가 알고리즘의 거대한 철제 용광로 속으로 소모품처럼 흡수되는 현실. 이 작품은 무자비한 기술 독점이 가리는 창작자의 숭고한 인간 노동 존엄성을 우람한 기술 구조와 붓을 든 연약한 소녀의 대조로 그려냅니다. 기술 발전이라는 화려한 구호가 결코 개인들의 땀방울을 무임승차해서는 안 되며, 가치 교환의 정의로움을 함께 회복해야 함을 고할 뿐만 아니라, 깊은 성찰의 여운을 독자들에게 영속 부과합니다.",
    thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-11",
    likes: 312,
    category: "만평",
    isApproved: true,
  },

  // 5. 에세이
  {
    id: "ess1",
    title: "[이솔에세이] 빗방울 머금은 돌담길, 한적한 오후의 커피와 사색",
    author: "서연 작가",
    reporterId: "admin",
    content: "지하철 환풍구의 더운 바람과 속도전에 끌려다니던 무거운 다리를 이끌고 당도한 작은 노포 앞 돌담길. 후드득 떨어지는 장마철 빗방울들은 세상을 잠시 고요한 주파수로 덮어 줍니다. 따뜻한 에스프레소 한 잔을 손에 쥐었을 때 전해지는 온기는 바삐 달려가느라 목적지를 망각하고 있던 현대인들에게 묻습니다. '우리는 지금 어디를 향해 그토록 조급히 뛰고 있는가?' 조용한 돌 틈에 비친 빗물 웅덩이는 흘려보낸 감정의 조각들을 정갈하게 거울처럼 비춰주며 가슴 깊은 곳 한 줄기 따사로운 평온을 부어줍니다.",
    thumbnail: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-12",
    likes: 312,
    category: "에세이",
    isApproved: true,
  },
  {
    id: "ess2",
    title: "[이솔에세이] 졸업 앨범의 낡은 종이 질감에서 환기되는 시절의 선율",
    author: "지우 작가",
    reporterId: "admin",
    content: "책꽂이 구석 구스름하게 먼지 쌓여 있던 고등학교 시절 졸업 앨범을 열었을 때, 바랜 종이 특유의 냄새와 함께 그 시절 풋풋하고 치기 넘쳤던 단어들이 귓전을 스칩니다. 이제는 각자의 직위와 사회적 역할을 지키느라 서로 다른 하늘 아래서 분투하는 친구들이지만, 세상을 더 친절하고 정의롭게 변화시키자며 주먹을 쥐고 다짐했던 그 시절 순수한 결심은 여전히 지문처럼 앨범 속에 고스란히 찍혀 있습니다. 이 짧은 사색은 닳아버린 마음의 태엽을 다시 기분 좋게 되감아줍니다.",
    thumbnail: "https://images.unsplash.com/photo-1497633762265-9a177c80b50b?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-09",
    likes: 198,
    category: "에세이",
    isApproved: true,
  },

  // 6. 사는이야기+
  {
    id: "life1",
    title: "주말 베란다 미니 농장 열풍: 한 뼘 흙 상자가 제공하는 생명의 안식",
    author: "농부인척",
    reporterId: "admin",
    content: "답답한 아파트 숲속 베란다에 마련한 단 한 평의 흙 상자 속에서 매일 새로운 서약이 일어납니다. 보잘것없어 보이던 작고 동그란 상추 씨앗이 비집고 올라오는 고요한 싹을 보며, 지친 퇴근길에 귀가하는 이들은 숨 가쁘던 도심의 속도를 잊고 생명의 위대함 앞에 숙연해집니다. 물 한 잔에 감사하고, 아주 미세한 초록빛 햇살 조각 하나에 잎을 틔워 결실을 선물하는 정직한 무농약 미니 정원은, 인간 역시 흙과 생명으로 숨 쉬는 지극히 연약하고도 찬란한 자연의 일원임을 감동 어린 농부 기고로 전합니다.",
    thumbnail: "https://images.unsplash.com/photo-1558444458-5cd00bb835ec?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-13",
    likes: 67,
    category: "사는이야기+",
    isApproved: true,
  },
  {
    id: "life2",
    title: "동네 따뜻한 단골 붕어빵 트럭 사장님의 아름다운 우정 장부",
    author: "이웃사촌",
    reporterId: "admin",
    content: "시린 동절기 영하의 바람을 등받이 삼아 20년째 길모퉁이를 지켜오신 김씨 아저씨의 작은 붕어빵 화통. 그 수레 안쪽에는 꼬깃꼬깃 세월을 적은 기묘한 외상 장부가 있습니다. 형편이 어렵거나 홀로 지내는 학생 지망생들에게는 항상 두 알씩 보태어 건네던 고독한 사장님의 깊은 사랑은 돈이라는 논리로 계산할 수 없는 인생 철학의 한 권 도서와 같습니다. 남은 잔액의 일부를 익명으로 동사무소 소외 연대 기금함에 밀어 넣는 사장님의 튼튼한 손은 고통과 자비의 위로를 골목길에 매일 피워내고 있습니다.",
    thumbnail: "https://images.unsplash.com/photo-1512132411229-c30391241dd8?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-10",
    likes: 128,
    category: "사는이야기+",
    isApproved: true,
  },

  // 7. 지역
  {
    id: "reg1",
    title: "우리 골목길 도시 문화 프로젝트: '이솔나라 페스타' 현장에 가다",
    author: "지역지기",
    reporterId: "admin",
    content: "대자본 복합 쇼핑몰에 밀려 점차 침체되어 가던 지역 골목 상인들이 공방 작가들과 연대하여 청년 중심 of 공예 축제를 성황리에 개최했습니다. 청년 디자이너들과 노령의 전통 공예가들이 멘토링 결연을 자처해 만든 수공예품 판매와 전통 민요 버스킹 행사는 죽어가던 회색빛 상권에 다시 사람들의 미소와 온기 넘치는 발자욱을 돌려 놓았으며, 지역 주민들이 스스로 힘을 한데 뭉쳤을 때 이뤄낼 수 있는 기분 조화로운 풀뿌리 자선 공동체의 든든함을 증명했습니다.",
    thumbnail: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-15",
    likes: 78,
    category: "지역",
    isApproved: true,
  },
  {
    id: "reg2",
    title: "원도심 빈 공간의 문화적 변신: 청년 예술가 상생 거점 공간으로 거듭나기",
    author: "도시인",
    reporterId: "admin",
    content: "공동화 단계를 가속하여 버려졌던 원도심의 철공소 건물이, 장애를 가진 청년 조각가들과 다문화 가정 아이들이 모여 머리를 맞대고 진흙 토기를 빚는 소박하고 우아한 배움터로 탈바꿈했습니다. 빈 콘크리트 상자 안에 침묵대신 아이들의 웃음소리가 스미기 시작했습니다. 세련되고 도회적인 도시 재생 이론 지표를 지면으로 설파하는 대신, 실제로 구르는 틈새 골목에서 상처받은 외톨이 예술가들이 어린 꿈나무들의 작은 수호자가 되어 주는 감동 어린 하모니 현장을 조명합니다.",
    thumbnail: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-14",
    likes: 62,
    category: "지역",
    isApproved: true,
  },

  // 8. 특별면
  {
    id: "spec1",
    title: "특별 기획: 대한민국 성장의 정체와 인구 감소, 2030세대의 진짜 속내",
    author: "특별취재팀",
    reporterId: "admin",
    content: "현재 2030 세대들과 청년들의 고유한 아픔인 결혼 및 출산 기피 현실을 두고, 단순히 정부나 시 차원의 현금성 지원 보조금 지급으로 해결될 것이라 보는 것은 너무나 얄팍한 시각입니다. 이 시대를 부유하는 젊은 영혼들의 진짜 속살을 들어보니, 그 속에는 타인과의 쉼 없는 비교, 무한 경쟁 속에서 느끼는 깊은 패배감과 미래 생존에 대한 근원적인 허무함이 도사리고 있었습니다. 이솔나라 특별 보도팀은 청년들에게 단순 자산 증식 대책을 들이미는 대신, 일상에서 실패하더라도 언제든 든든히 감싸 안아주는 상생의 사회 안전망과, 각자의 존엄을 있는 그대로 존중해 주는 심도 깊은 정서 치료 정책이 선행되어야 함을 눈물 어린 청년 가구 밀착 인터뷰를 통해 준엄하게 역설하고 있습니다.",
    thumbnail: "https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-15",
    likes: 420,
    category: "특별면",
    isApproved: true,
  },
  {
    id: "spec2",
    title: "심층 보도: 이상기후 충격과 글로벌 푸드 밸류 체인 위기 대응 시나리오",
    author: "특별취재팀",
    reporterId: "admin",
    content: "지구의 반대편에서 신음하는 보이지 않는 들풀과 가뭄 수치는 결코 먼 나라의 이야기가 아닙니다. 기습적인 냉해와 이상 고온 현상으로 전 세계 곡물 선물 단가가 겉잡을 수 없이 출렁이는 이 시점에서, 우리는 식품 밸류 체인의 붕괴를 맞이하고 있습니다. 하지만 이솔특집팀은 정량의 수치 지표 나열에서 그치지 않고, 기후 난민으로 전락하고 있는 저개발국 농가들의 가쁜 한숨과 땀방울을 직접 타전했습니다. 생존을 위해 대를 이어 일구던 흙밭이 사막으로 굳어지는 고통 속에서도 소농들과 우리가 하나의 푸른 지구 안에서 보이지 않는 실타래로 연결되어 있음을 자각하고, 함께 친환경 소비와 탄소 상생 연합 전선을 이룩해 나가는 가슴 뜨거운 연대만이 모두를 구할 진짜 열쇠입니다.",
    thumbnail: "https://images.unsplash.com/photo-1623126389902-6c846c8ee6e8?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-13",
    likes: 256,
    category: "특별면",
    isApproved: true,
  },

  // 9. 시리즈
  {
    id: "ser1",
    title: "[연속 기획] 모바일 너머 가상 공간으로 점프하는 '디지털 네이티브'들의 가치 지도 - 1부",
    author: "트렌드팀",
    reporterId: "admin",
    content: "태어날 때부터 모니터 키보드가 아닌 대화형 인공지능 인터페이스와 자율 아바타 가상 세계와 대화하며 공감각을 활성화해 온 영 프로 연령층의 도덕 지각력을 다양한 뇌 과학과 문화학 관점으로 해부한 국내 독보 연재 기획입니다.",
    thumbnail: "https://images.unsplash.com/photo-1535223289827-42f1e9919769?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-15",
    likes: 112,
    category: "시리즈",
    isApproved: true,
  },
  {
    id: "ser2",
    title: "[연속 기획] 제2막 생명 수호 숲 보존 캠페인을 일구는 청년 은퇴 가이들의 도약 - 3부",
    author: "창업가이드",
    reporterId: "admin",
    content: "어메니티가 충족된 세련된 도시 직업군을 은퇴하고 산과 들에 모여 천연 생태 식목 연구와 도심 무농약 푸드 숲을 가꿔 유통하는 주주 협동조합의 탄생 모델과 지속 가능 실천법의 핵심 가이드 백서를 상세 전수합니다.",
    thumbnail: "https://images.unsplash.com/photo-1454165833767-027ffea9e77b?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-14",
    likes: 85,
    category: "시리즈",
    isApproved: true,
  },

  // 10. 논쟁
  {
    id: "deb1",
    title: "[맞수 토론] 생성형 AI 이미지 모델 가동, 저작권의 엄밀한 보호 vs 소셜 공유 오픈소스 활성화",
    author: "여론광장",
    reporterId: "admin",
    content: "창작 화백들의 혼이 담긴 작업 원화를 데이터로 학습하는 AI 드로잉 머신의 도덕 문제를 두고 권익 보호를 우선시해야 한다는 엄단파와 누구나 고품격 화풍을 도구 삼아 문화를 즐길 공유 권한이 있다는 활성화파의 의견을 팽팽하게 종합 중계합니다.",
    thumbnail: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-15",
    likes: 532,
    category: "논쟁",
    isApproved: true,
  },
  {
    id: "deb2",
    title: "[핫 이슈] 도심 탄소 제로 실현을 위한 재생 소형 풍력 발전기 다수 설비, 경치 훼손 조망권 논쟁",
    author: "여론광장",
    reporterId: "admin",
    content: "친환경 기후 위기 극복의 상징으로 여겨지는 마이크로 수직 풍력 날개 모터 탑을 마을 중심 주거 옥상에 배치하여 전력을 수급하는 국정 시책에 대해, 에너지 자급 자족 의의와 흉물스러운 저주파 소음 및 경관 삭막화를 지적하는 마찰이 도마에 올랐습니다.",
    thumbnail: "https://images.unsplash.com/photo-1516767839131-7892534574c7?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-12",
    likes: 345,
    category: "논쟁",
    isApproved: true,
  },

  // 11. 팩트체크
  {
    id: "fact1",
    title: "[팩트체크] 완전 무수 수소 보급 트럭, 가동 공정 및 물류 탄소 지표가 정말 일반 화물보다 낮을까",
    author: "이솔팩트",
    reporterId: "admin",
    content: "친환경 교통으로 선전되는 수소 모터 운송의 생산 단계부터 수소 가스 추출, 냉각 압축 압송 충전으로 소모되는 화석 에너지를 포함한 기후 전수 조사 지표를 소방청 및 해외 탄소 연구 학술 통계를 연결하여 투명하고 정직하게 팩트 비교해 드립니다.",
    thumbnail: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-15",
    likes: 890,
    category: "팩트체크",
    isApproved: true,
  },
  {
    id: "fact2",
    title: "[팩트체크] 기계 수거형 폐플라스틱 의류 가공 공장, 실제 탄소 비중 검증 결과",
    author: "이솔팩트",
    reporterId: "admin",
    content: "석유계 합성 섬유 화학 원단을 재활용해 만든 기부 패딩 의류가 환경 정화 효과를 낼지 아니면 미세 플라스틱 가공 세척수 유출량에 있어 역설적 환경 피해를 가속 시킬지 전문가 화학 학정 심사를 입체 조사한 최신 팩테데이터 보고서 내용 전문입니다.",
    thumbnail: "https://images.unsplash.com/photo-1574607383476-f517f220d398?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-11",
    likes: 432,
    category: "팩트체크",
    isApproved: true,
  },

  // 12. 이솔나라스타
  {
    id: "star1",
    title: "[스타인터뷰] 연극 무대와 스크린을 넘나드는 불멸의 영혼, 예술가 한이슬 독점 수놓기",
    author: "강기자",
    reporterId: "admin",
    content: "스포트라이트의 화려함보다도 한 편의 깊이 있는 예술 독립극에 자신의 주체성과 혼을 모두 녹여내 소통하려는 전천후 액터 한이슬을 만나, 그녀가 추구하는 비건 창작 철학과 디지털 특이점 관용도의 진솔한 고민 장부를 함께 들여다봤습니다.",
    thumbnail: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-12",
    likes: 856,
    category: "이솔나라스타",
    isApproved: true,
  },
  {
    id: "star2",
    title: "[무대 클로즈업] 인디 퓨전 밴드 '블루노트'가 창시하는 뉴 국악 얼터너티브 사운드 현장",
    author: "연예투데이",
    reporterId: "admin",
    content: "전통 대금 해금과 일렉트릭 신디사이저가 빚어내는 장엄하고 파괴적인 사이키델릭 전통 화음. 전석 매진을 기록하는 라이브 콘서트 현장의 뜨거운 생명력을 열정 넘치는 기사 글과 웅장한 무대 뒷이야기로 장식합니다.",
    thumbnail: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-11",
    likes: 1204,
    category: "이솔나라스타",
    isApproved: true,
  },

  // 13. 이솔나라포토
  {
    id: "photo1",
    title: "[포토뉴스] 차가운 새벽 서리를 품은 이솔나라 겨울 정원의 우아한 소품화",
    author: "박작가",
    reporterId: "admin",
    content: "아침 태양이 피어오르기 직전, 유리 조각 같은 서리가 초록 잎사귀 표면에 맺혀 보석처럼 빛나는 자연 예술의 극적 영도를 정밀 장노출 흑백 접사 사진 예술로 영구 봉인한 감동 시선 시리즈 중 일환입니다.",
    thumbnail: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-12",
    likes: 310,
    category: "이솔나라포토",
    isApproved: true,
  },
  {
    id: "photo2",
    title: "[포토뉴스] 도시의 맥박과 쉼 없는 차들의 은빛 하모니 장노출 파노라마",
    author: "도시기록자",
    reporterId: "admin",
    content: "도심 순환 고가도로 위를 정비 지나는 빨갛고 하얀 불빛들의 꼬리표가 거대한 네오 미래 도심의 혈액 혈관처럼 조형된 순간을 차분하게 포착하여 복잡한 도시 생활의 역동적 고독을 표현해 냈습니다.",
    thumbnail: "https://images.unsplash.com/photo-1533929736458-ca588d08c8be?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-10",
    likes: 278,
    category: "이솔나라포토",
    isApproved: true,
  },

  // 14. 이솔나라TV
  {
    id: "tv1",
    title: "[TV 뉴스] 이솔나라 국영 비건 AI 스튜디오 개소 현장 밀착 녹화 중계",
    author: "영상취재팀",
    reporterId: "admin",
    content: "수작업 창작 예술가들과 윤리적 기계 미디어가 결합하여 전 생명 친화 콘텐츠를 매일 송출 개시하는 첨단 무비 연구 공간의 오프닝 세레모니를 활기찬 목소리로 구성한 프리미엄 현장 영상 중심 보도본부 리포트입니다.",
    thumbnail: "https://images.unsplash.com/photo-1518176259641-0ed67515bd14?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-12",
    likes: 156,
    category: "이솔나라TV",
    isApproved: true,
  },
  {
    id: "tv2",
    title: "[TV 다큐] 시간이 멈춘 철도 간이역, 선로 위를 수놓는 역장의 50년 기차가 들려준 단상",
    author: "다큐공감",
    reporterId: "admin",
    content: "하루 단 두 차례만 무궁화호가 경유하는 조용하고 한적한 시골의 노스탤지어 역. 수동 선로 신호 장치 배선을 평생 점검 보살펴 온 정겨운 역장님 손마디 주름사이에 서려 있는 깊이 있는 동행 이야기를 담았습니다.",
    thumbnail: "https://images.unsplash.com/photo-1543083507-993474e0d9b4?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-09",
    likes: 89,
    category: "이솔나라TV",
    isApproved: true,
  },

  // 15. 10만인클럽
  {
    id: "club1",
    title: "[10만인클럽] 진리와 공의의 메신저를 자처하는 이솔나라 주주연대 창립 대회",
    author: "나눔천사",
    reporterId: "admin",
    content: "거대 정언 유착 자본의 상업적 조작이나 보도 장벽 압박으로부터 자유롭고, 순수 독립 생태 평화 가치를 지키기 위하여 10만 명의 시민 저널리스트들이 십시일반 힘을 연대해 독립 언론사를 격려 보살피는 연대 포럼 소식입니다.",
    thumbnail: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-12",
    likes: 412,
    category: "10만인클럽",
    isApproved: true,
  },
  {
    id: "club2",
    title: "[10만인클럽] 제로 플라스틱 친환경 운동 실천 릴레이 인증 캠페인 목표 돌파 소식",
    author: "에코전사",
    reporterId: "admin",
    content: "생활 속 불필요한 일회용기 포장을 사절하고 텀블러 보급 및 천 주머니 장보기를 주간 인증하는 10만인클럽 회원들의 소셜 풀뿌리 서명 동참 이벤트를 집중 종합 보도합니다. 풀뿌리 나눔을 통해 건강한 내일을 지킵니다.",
    thumbnail: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-10",
    likes: 324,
    category: "10만인클럽",
    isApproved: true,
  },

  // 16. 이솔공방
  {
    id: "cosmic_masterpiece",
    title: "[이솔공방 특별전시] 우주의 살아있는 생명 나무 (Cosmic Tree of Life) - 초현실주의 걸작 오일 아트",
    author: "이솔공방 중앙 아티스트",
    reporterId: "admin",
    content: "이솔공방 화백단과 최첨단 AI 기법이 유기적으로 결합하여 완성한 기념비적 오일 페인팅 걸작입니다. 하늘하늘 뻗어 나가는 신성한 가지들은 찬란하게 빛나는 성운과 행성계로 이어지며, 영원의 지혜를 품은 빛나는 우주 과실을 맺습니다. stardust(성단 먼지)와 액체광(liquid light)으로 짜여진 빛나는 뿌리는 대지 깊은 곳의 정신 생명력과 우주 전체를 긴밀히 연결하며, 감상자에게 우주적 연대와 깊은 사유, 형언할 수 없는 영성적 경외감을 선사합니다. 이솔나라가 제안하는 기술 인문학적 미학의 정수이자 한 편의 대서사시입니다.",
    thumbnail: "/src/assets/images/cosmic_masterpiece_1784129393714.jpg",
    date: "2026-07-15",
    likes: 999,
    category: "이솔공방",
    isApproved: true,
    isFeatured: true,
  },
  {
    id: "wshop1",
    title: "[이솔공방] 한지 직조 공예: 우리의 한지가 자아내는 천연 가구 가치 재발견",
    author: "이지은 화백",
    reporterId: "admin",
    content: "천연 닥나무 섬유질을 전통 공법으로 펴내고 옻칠을 가하여 가벼우면서도 대를 이어 반영구 보전할 수 있는 친환경 한지 공방 수공예 제품들의 유려한 색감과 제작 과정을 집중 밀착 취재하여 기고합니다.",
    thumbnail: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-14",
    likes: 195,
    category: "이솔공방",
    isApproved: true,
  },
  {
    id: "wshop2",
    title: "[이솔공방] 교보출판과 합작하는 고품격 우드 아트 굿즈 기획 프로젝트",
    author: "이솔공방 화백",
    reporterId: "admin",
    content: "친환경 재생 목재 재목과 전통 활자 폰트 디자인을 융합하여 서재와 책상 위에 지혜의 향기를 피워낼 수 있는 도서 소품 책꽂이 및 독서 플레이트 제작 프로젝트를 교보출판 크리에이터 노드들과 협업 기획 보고합니다.",
    thumbnail: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-13",
    likes: 134,
    category: "이솔공방",
    isApproved: true,
  },

  // 17. 이솔나라북
  {
    id: "book_isl1",
    title: "[이솔나라북] 정보 과부하의 홍수 시대 속, 우리의 인문학적 독서 방패와 느리게 걷기",
    author: "책벌레",
    reporterId: "admin",
    content: "자고 일어나면 미디어 전파 쓰레기와 쇼츠 자극 영상이 쏟아져 기억력을 단절시키는 현상 속에, 소박하고 무거운 페이퍼 서적을 침묵 가운데 한 쪽씩 공들여 음미하는 행위가 주는 가득 찬 정신 보전 치료 가이드 북리뷰.",
    thumbnail: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-12",
    likes: 215,
    category: "이솔나라북",
    isApproved: true,
  },
  {
    id: "book_isl2",
    title: "[이솔나라북] 고전 희곡 속에 숨겨진 현대인의 사회적 관계성 해설 인터뷰 보고서",
    author: "문학여행",
    reporterId: "admin",
    content: "셰익스피어의 맥베스, 도스토옙스키의 카라마조프 가의 형제들 속에 나타나는 인간 탐욕의 본심과 화해 메커니즘을 오늘날 사회 갈등 문제의 완화제 솔루션 키로 치열하게 재인증 재해석하려는 깊이 깊은 북 라운지 강연입니다.",
    thumbnail: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-08",
    likes: 187,
    category: "이솔나라북",
    isApproved: true,
  },

  // 18. AI 기사
  {
    id: "ai_repr1",
    title: "[AI 종합분석] 2026년 하반기 탄소제로 국가 연합 기술 흐름과 미래 친환경 지형도",
    author: "AI 기자",
    reporterId: "admin",
    content: "인공지능 정형 시뮬레이션 알고리즘 노드가 전 세계 에너지 소비 지표 및 지자체 친환경 스마트 규제 동향 빅데이터 패러다임을 종합 취합해, 6개월 뒤 전 지구적 재생에너지 공급량 추이를 장차 정밀 예측해 드립니다.",
    thumbnail: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-12",
    likes: 542,
    category: "AI 기사",
    isApproved: true,
  },
  {
    id: "ai_repr2",
    title: "[AI 에세이웨어] 고도로 밀집된 도심 소외 속 피어나는 역설적 메타 소셜 네트워킹",
    author: "AI 기자",
    reporterId: "admin",
    content: "물리적 만남은 줄고 가상 아바타 교류량은 확대되는 주거 연령대 비율 통계표를 바탕으로 메타 소설 알고리즘이 현대 청년들의 외로움 극복 행동 양식을 르포 형태 문체로 직접 생성 작성해 선보이는 독창 보도입니다.",
    thumbnail: "https://images.unsplash.com/photo-1618042164419-39adad42d113?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-11",
    likes: 418,
    category: "AI 기사",
    isApproved: true,
  },

  // 19. 온에어
  {
    id: "onair_mov1",
    title: "[온에어] 현원 감독, 한국 첫 AI영화사 ‘비건AI무비’ 설립으로 시네마틱 새 지평 선언",
    author: "정길종 기자",
    reporterId: "admin",
    content: "한국 최초의 생성형 AI 기반 영화사인 ‘비건AI무비(Vegan AI Movie)’가 2026년부터 본격적으로 작품 활동의 신호탄을 쏘아 올립니다. 창립자인 거장 현원 감독은 물리적인 탄소 배출과 현장 낭비 요소를 제로화하는 인공지능 기반 디지털 제작 공정을 전격 선포하며, 지구와 생명을 보듬는 지속 가능하고 따뜻한 미장센을 선보일 예정입니다.",
    thumbnail: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-25",
    likes: 234,
    category: "온에어",
    isApproved: true,
  },
  {
    id: "onair_mov2",
    title: "[온에어] 현원 감독, “AI 배우 ‘이솔’과 더 비건스(The Vegans)로 인류와 지구를 위한 예술 가치 치유”",
    author: "정길종 기자",
    reporterId: "admin",
    content: "독립영화 거장 현원 감독은 세계 최초의 AI 예술가 5인(이솔, 라온, 가온, 아린, 다온)으로 구성된 메타버스 가상 연기팀 ‘더 비건스’ 프로젝트를 추진한다고 발표했습니다. 가상의 AI 예술가들을 통해 단순히 차가운 컴퓨터 코드가 아니라, 감성과 홀로그램 가창, 감미로운 예술의 빛으로 현대인의 상처를 치유하는 따뜻하고 평화로운 우주적 영혼의 에너지를 불어넣겠다는 구상입니다.",
    thumbnail: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-26",
    likes: 156,
    category: "온에어",
    isApproved: true,
  },
  {
    id: "onair_mov3",
    title: "[온에어] ‘비건AI무비’의 지속가능성... 탄소 제로 디지털 영화 제작 공정의 혁신",
    author: "환경생태팀",
    reporterId: "admin",
    content: "현원 감독이 주창하는 '비건AI무비'의 가치는 식생활을 넘어선 영화 예술계의 근본적 혁신입니다. 세트장 가설 및 촬영용 디젤 전력차 등 야생 생태계에 큰 발자국을 입혔던 전통적 제작 과정을 하이테크 AI 연출 기법으로 전환하여, 완벽한 탄소 배출 제로(Carbon Zero)의 환경 친화적 영화를 현실화한 공로로 글로벌 독립영화 평단의 뜨거운 관심을 한 몸에 받고 있습니다.",
    thumbnail: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-27",
    likes: 195,
    category: "온에어",
    isApproved: true,
  },

  // 20. 특별 Promos (구독PICK, 후원계좌, 복지부통장)
  {
    id: "promo_pick1",
    title: "[구독PICK] 2026 중소 자영 소상공인 무이자 탄소 감축 기금 정책 안내 단독 보고서",
    author: "경제왕",
    reporterId: "admin",
    content: "정보 소외로 정부 혜택을 놓치기 쉬운 영세 수공예 상인과 가내 유통 상인들을 지원하는 도심 스마트 기금 무이자 융자 경로를 보기 쉽게 종합 짚어 드립니다.",
    thumbnail: "https://images.unsplash.com/photo-1554224155-1197a5bb126e?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-14",
    likes: 89,
    category: "구독PICK",
    isApproved: true,
  },
  {
    id: "promo_pick2",
    title: "[구독PICK] 디지털 독립 노마드로 살아가기 위한 업무 보안 및 장소 독립 훈련 지식 장부",
    author: "방랑자",
    reporterId: "admin",
    content: "이솔나라 전용 위성망과 보안 가상 사설망 클라이언트 노드 활성화를 활용하여 거주지에 속박당하지 않고 소외 골목 어디서나 독립 기사 글을 집필하는 전문가 노하우 가이드.",
    thumbnail: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-11",
    likes: 56,
    category: "구독PICK",
    isApproved: true,
  },
  {
    id: "promo_spons1",
    title: "[후원기사] 진실을 향한 맑고 정직한 독립 기사의 타전, 여러분의 후원 계좌가 보장합니다",
    author: "독립언론사연대",
    reporterId: "admin",
    content: "독립 언론 법의 준수 아래 가짜 뉴스와 황색 찌라시 보도 전파를 일절 거단하고, 생명 독립 비건 정보 사상을 시민 주도적으로 연대하기 위한 정기 소식 후원 플랫폼 동참 지면입니다.",
    thumbnail: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-12",
    likes: 1045,
    category: "후원계좌",
    isApproved: true,
  },
  {
    id: "promo_spons2",
    title: "[복지부] 이솔나라 소외 계층 기초 자금 지원을 담당하는 전용 복지부통장 캠페인 현황 소식",
    author: "복지위원회",
    reporterId: "admin",
    content: "주민들의 소중한 투명 기부금과 국영 친환경 세수가 모여, 차상위 소외 및 긴급 치료 수술을 고대하는 도심 이웃 가구에 100% 온전히 집행되는 복지부 전용 계좌 소통 지면입니다.",
    thumbnail: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=800",
    date: "2026-05-08",
    likes: 2156,
    category: "복지부통장",
    isApproved: true,
  },
  {
    id: "real_human_photo_1",
    title: "[리얼포토] 안개 속을 뚫고 지나가는 정동진 바다열차의 실경",
    author: "김도균 작가",
    reporterId: "admin",
    content: "바쁘게 생성형 AI 이미지가 쏟아지는 초정밀 인텔리전스 시대에, 새벽 5시 정동진 해변에 삼각대를 세우고 인간의 호흡과 기다림의 미학으로 직접 담아낸 실사(Real Photo) 풍경입니다. 차갑고 푸른 새벽의 해무와 멀리서 붉게 떠오르는 태양 사이를 무심히 지나가는 바다열차의 역동적인 순간을 렌즈 프레임 안에 물리적으로 기록하였습니다. AI 연산이나 정형화된 모델링 가상 보정을 전혀 거치지 않은, 순수 렌즈 광학이 포착해낸 가치 있는 ‘진짜 소중한 세계’의 일면입니다. 찬란한 빛의 스펙트럼을 직접 눈으로 보듯 현장 그대로의 기운을 담았습니다.",
    thumbnail: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800",
    date: "2026-07-15",
    likes: 582,
    category: "리얼포토",
    isApproved: true,
    isHumanTaken: true,
    cameraModel: "Sony A7R V",
    lensModel: "FE 70-200mm F2.8 GM OSS II",
    locationTaken: "강원 강릉시 정동진역 동해안 해변",
    isoSpeed: "100",
    apertureValue: "F4.0",
    shutterSpeed: "1/160s",
  },
  {
    id: "real_human_photo_2",
    title: "[리얼포토] 노량진 수산시장 상인의 미소와 갓 잡은 전어의 은빛 숨결",
    author: "윤창호 작가",
    reporterId: "admin",
    content: "새벽 경매장의 치열한 외침과 비린내 가득한 인간 삶의 가장 역동적인 일터를 직접 동행하며 촬영한 다큐멘터리식 휴먼 라이트 사진입니다. 상인의 투박하고 굳은살이 얹어진 고무장갑 위에서 역동적으로 펄떡이는 전어의 날것 그대로의 은빛 비늘은 그 어떠한 알고리즘이나 픽셀 렌더링으로도 고스란히 복제해 낼 수 없는 오리지널리티의 상징입니다. 이마에 맺힌 구슬땀과 환하게 웃어주신 상인 어르신의 눈가 주름에서 가짜가 만연하는 세상 속 '인간의 뜨거운 진실성'을 다시금 느끼게 합니다.",
    thumbnail: "https://images.unsplash.com/photo-1534482421-64566f976cfa?auto=format&fit=crop&q=80&w=800",
    date: "2026-07-14",
    likes: 421,
    category: "리얼포토",
    isApproved: true,
    isHumanTaken: true,
    cameraModel: "Fujifilm X-T5",
    lensModel: "XF 35mm F1.4 R",
    locationTaken: "서울 동작구 노량진 수산시장 내 경매장",
    isoSpeed: "400",
    apertureValue: "F1.4",
    shutterSpeed: "1/250s",
  },
  {
    id: "real_human_photo_3",
    title: "[리얼포토] 한강대교 위에서 담아낸 퇴근길 자동차 불빛의 30초 장노출 궤적",
    author: "이솔미 기록가",
    reporterId: "admin",
    content: "30초라는 물리적 시간의 기나긴 노출 동안 차갑게 한강을 건너간 수만 대의 자동차들이 겹겹이 남긴 붉고 따뜻한 불빛의 궤적(Light Trail)입니다. 이것은 가상 시뮬레이션의 수학적 곡선이 아니라, 오늘 하루도 성실하게 일터를 지키고 마침내 사랑하는 가정이 있는 집을 향해 성실히 달려가는 우리네 진짜 인생들의 온기와 호흡을 장시간 한 필름 프레임 안에 응축해낸 경이로운 풍경화입니다. 인간 촬영가만이 가질 수 있는 도시를 향한 따뜻하고 연민 넘치는 시선으로 이 장관을 직조했습니다.",
    thumbnail: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&q=80&w=800",
    date: "2026-07-13",
    likes: 673,
    category: "리얼포토",
    isApproved: true,
    isHumanTaken: true,
    cameraModel: "Canon EOS R5",
    lensModel: "RF 24-105mm F4 L IS USM",
    locationTaken: "서울 한강대교 북단 강변북로 진입로 전망대",
    isoSpeed: "50",
    apertureValue: "F11",
    shutterSpeed: "30s",
  },
];
